use_frameworks!

platform :ios, '9.0'

target 'BronLib_Example' do
  pod 'BronLib', :path => '../'

  target 'BronLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
